# Generated by Django 3.1.7 on 2021-05-05 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'answer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QnaCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'QnA_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('Objective', 'Objective'), ('Subjective', 'Subjective')], max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('category_type', models.ManyToManyField(to='QnA.QnaCategory')),
                ('ques_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectedQnA',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ManyToManyField(blank=True, to='QnA.Answer')),
                ('ques_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_sender', to=settings.AUTH_USER_MODEL)),
                ('question', models.ManyToManyField(blank=True, to='QnA.Question')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SelectedQnA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_1', models.CharField(blank=True, max_length=100, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=100, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=100, null=True)),
                ('choice_4', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set_question', to='QnA.question')),
            ],
            options={
                'verbose_name_plural': 'choice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set_question', to='QnA.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
