# Generated by Django 3.1.7 on 2021-05-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedqna',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
