# Generated by Django 3.1.7 on 2021-05-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QnA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ques_answer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='is_match',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_active',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ques_sender',
        ),
        migrations.RemoveField(
            model_name='qnacategory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='question',
            name='ques_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SelectedQnA',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ManyToManyField(blank=True, to='QnA.Answer')),
                ('ques_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_sender', to=settings.AUTH_USER_MODEL)),
                ('question', models.ManyToManyField(blank=True, to='QnA.Question')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SelectedQnA',
            },
        ),
    ]
