# Generated by Django 3.1.7 on 2021-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_auto_20210504_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category_type',
        ),
        migrations.AddField(
            model_name='question',
            name='category_type',
            field=models.ManyToManyField(related_name='question_set_category', to='QnA.QnaCategory'),
        ),
    ]
