# Generated by Django 3.1.7 on 2021-05-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0006_auto_20210504_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
    ]
