# Generated by Django 3.1.7 on 2021-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0007_remove_question_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ques_answer',
        ),
    ]
