# Generated by Django 3.1.7 on 2021-05-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0008_remove_question_ques_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='receiver',
        ),
    ]
