# Generated by Django 3.1.7 on 2021-05-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0010_auto_20210504_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'question'},
        ),
    ]
